Removing ubuntu:xenial from testing script and adding a drop to a debug shell when package installation fails.

diff --git a/ps-install-tester b/ps-install-tester
--- a/ps-install-tester
+++ b/ps-install-tester
@@ -19,3 +19,10 @@ fi
 # Install the package
 apt-get -y install $PKG
 
+# Debug if install failed
+if [[ "$2" && $? -ne 0 ]]; then
+    echo -e "\n\033[1;33mWe've been given a second argument and the install failed, we'll run this.\033[0m\n"
+    $2
+    exit 1
+fi
+
